# Generated by Django 6.0.4 on 2026-04-24 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0002_alter_healthupdate_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthupdate',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
